//! Golden outputs generated by `manif-geom-cpp` at commit
//! `d976fb0d397d6a69656d0548fe33be50b583ed20`.
//!
//! These values make convention drift visible across the two implementations,
//! especially coefficient order, composition order, and tangent ordering.

// Preserve the decimal strings emitted by the C++ probe verbatim.
#![allow(clippy::excessive_precision)]

use manif_geom_rs::{na, SE2d, SE3d, SO2d, SO3d};

const TOLERANCE: f64 = 1.0e-13;

fn assert_close(actual: &[f64], expected: &[f64]) {
    assert_eq!(actual.len(), expected.len());
    for (index, (actual, expected)) in actual.iter().zip(expected).enumerate() {
        assert!(
            (actual - expected).abs() <= TOLERANCE,
            "coefficient {index}: expected {expected:.17}, got {actual:.17}"
        );
    }
}

#[test]
fn so2_matches_cpp_exponential_and_action() {
    let rotation = SO2d::exp_map(&na::Vector1::new(0.7));
    assert_close(
        rotation.elements().as_slice(),
        &[0.7648421872844885, 0.64421768723769102],
    );
    assert_close(
        (rotation * na::Vector2::new(1.2, -0.4)).as_slice(),
        &[1.1754976996364626, 0.4671243497714338],
    );
}

#[test]
fn so3_matches_cpp_exponential_and_action() {
    let rotation = SO3d::exp_map(&na::Vector3::new(0.2, -0.3, 0.4));
    assert_close(
        rotation.elements().as_slice(),
        &[
            0.96396848182616368,
            0.098796039321534662,
            -0.14819405898230198,
            0.19759207864306932,
        ],
    );
    assert_close(
        (rotation * na::Vector3::new(1.2, -0.4, 0.8)).as_slice(),
        &[1.0203480172842301, -0.13819083478404104, 1.0861828652698542],
    );
}

#[test]
fn se2_matches_cpp_exponential_action_composition_and_logarithm() {
    let transform = SE2d::exp_map(&na::Vector3::new(0.4, -0.2, 0.7));
    assert_close(
        transform.elements().as_slice(),
        &[
            0.4353123391973982,
            -0.04968630337333374,
            0.7648421872844885,
            0.64421768723769102,
        ],
    );
    assert_close(
        transform
            .transform_point(&na::Vector2::new(1.2, -0.4))
            .as_slice(),
        &[1.6108100388338609, 0.41743804639810006],
    );

    let other = SE2d::exp_map(&na::Vector3::new(-0.3, 0.5, -0.25));
    assert_close(
        transform.otimes(&other).elements().as_slice(),
        &[
            -0.13404323750583103,
            0.068918414345305712,
            0.90044710235267689,
            0.43496553411123012,
        ],
    );
    assert_close(
        SE2d::log_map(&transform).as_slice(),
        &[0.4, -0.20000000000000007, 0.7],
    );
}

#[test]
fn se3_matches_cpp_exponential_action_composition_and_logarithm() {
    let transform = SE3d::exp_map(&na::Vector6::new(0.4, -0.2, 0.7, 0.2, -0.3, 0.4));
    assert_close(
        transform.elements().as_slice(),
        &[
            0.33129919517024764,
            -0.20140947273869481,
            0.73329329786085506,
            0.96396848182616368,
            0.098796039321534662,
            -0.14819405898230198,
            0.19759207864306932,
        ],
    );
    assert_close(
        transform
            .transform_point(&na::Vector3::new(1.2, -0.4, 0.8))
            .as_slice(),
        &[1.3516472124544778, -0.33960030752273584, 1.8194761631307093],
    );

    let other = SE3d::exp_map(&na::Vector6::new(-0.3, 0.5, 0.1, -0.1, 0.25, 0.05));
    assert_close(
        transform.otimes(&other).elements().as_slice(),
        &[
            -0.16316657930426953,
            0.11478265153117412,
            0.80726698907478034,
            0.97341181243322228,
            0.021508145181318196,
            -0.038997995112521944,
            0.22469089764281153,
        ],
    );
    assert_close(
        SE3d::log_map(&transform).as_slice(),
        &[0.4, -0.2, 0.7, 0.2, -0.3, 0.4],
    );
}
